image: node:18-alpine

default:
  tags:
    - linux-local

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  script: npm run test

deploy:
  stage: deploy
  script: echo "Deploying..."
  dependencies: []