image: node:18-alpine

default:
  tags:
    - linux-local

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/


test:
  stage: test
  script:
    - npm install 
    - npm run test

deploy:
  stage: deploy
  script: echo "Deploying..."