name: pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install npm dependencies
      run: npm ci
    - name: Unit tests
      run: npm test

  deploy-to-S3:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying..."
    
