name: pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install NPM Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test
      - run: echo "Hello world this is it" > test.txt
      - run: ping -c 5 192.168.43.29
      - uses: actions/upload-artifact@v3
        with:
          name: dockerfile
          path: test.txt
 

  deploy-to-S3:
    needs: build-and-test
    runs-on: self-hosted
    container: amazon/aws-cli
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dockerfile
      - run: cat test.txt
      - run: aws --version
      - run: aws s3 cp test.txt s3://${{ secrets.AWS_S3_BUCKET }}/test.txt
    
